### ISSUE TITLE
Creating indexPath seems to always return nil

### ISSUE THREAD

**Issue by croossin** [Sweefties/iOS9-NewAPI-3DTouch-PeekAndPop-Example#1]
It seems whenever I enter the `previewingContext` function I return nil - I have debugged and found that it is from when I am trying to access indexPath here:

```
 guard let indexPath = tableView.indexPathForRowAtPoint(location),
            cell = tableView.cellForRowAtIndexPath(indexPath) else { return nil }
```

I am using custom cells in my tableView so I am not sure if that has anything to do with it.  I am sort of confused on `indexPathForRowAtPoint(location)` parameter `location`.  
Any explanation as to what could possibly be going wrong would be a great help! Thanks again for the awesome tutorial!

**Comment by Sweefties** [comment]
Hi,
Did you try this and debugged? : 

``` swift
// location point returned???
print(location) 

guard let indexPath = tableView.indexPathForRowAtPoint(location) else { return nil }
let cell = tableView.cellForRowAtIndexPath(indexPath)! as UITableViewCell //or your custom cell class
```

`location` must be return `CGPoint()` for `sourceView` cell in tableView.. required for `previewingContext.sourceRect`

**Comment by croossin** [comment]
Yes I printed the location and determined the CGPoint - my table view that I am trying to use 3d touch on is in the bottom portion of the main view, with another view above it.  The `location` is the correct `CGPoint` but for some reason when running
`guard let indexPath = tableView.indexPathForRowAtPoint(location) else { return nil }`
I am always getting nil.  `tableView.center` is returning the correct point on the screen so I am not sure why I am always getting nil

Any help would be much appreciated!

**Comment by Sweefties** [comment]
``` swift
let indexPath = tableView.indexPathForRowAtPoint(location)
print(indexPath)
```

`NSIndexPath` returned or not?
`indexPathForRowAtPoint` returns an index path representing the row and section associated with point, or nil if the point is out of the bounds of any row. Be sure your point is IN of the bounds of your row.

Else if no `indexPath` returns, try this in `viewDidLoad()` : 

``` swift
// Force touch feature
        if traitCollection.forceTouchCapability == UIForceTouchCapability.Available {
            // register UIViewControllerPreviewingDelegate to enable Peek & Pop
            registerForPreviewingWithDelegate(self, sourceView: tableView)
        }
```

`registerForPreviewingWithDelegate(self, sourceView: tableView)` with your tableView for sourceView

**Comment by croossin** [comment]
That fixed it! Now a lot more debugging... I had to change the sourceView to tableView.  Thank you again!

**Comment by HelloWilliam** [comment]
registerForPreviewing(with: self, sourceView: tableView)

the import is the source view ,it's must be tableview.

Thanks @Sweefties.
